function [Result] = mlFitting(Data, Config)

    [Result.MLfit.thetaMean    , ...
     Result.MLfit.muMean       , ...
     Result.MLfit.sigmaMean    , ...
     Result.MLfit.J_historyMean, ...
     Result.MLfit.errorMean]   = gradientDescent(Data.X, Data.Y, Config);
    
    Result.MLfit.fmean = @(x, y) Result.MLfit.thetaMean(1) + Result.MLfit.thetaMean(2)*x     + ...
                Result.MLfit.thetaMean(3)*y + Result.MLfit.thetaMean(4)*x^2 + ...
                Result.MLfit.thetaMean(5)*x*y + Result.MLfit.thetaMean(6)*y^2;
      
    
    [Result.MLfit.thetaStd    , ...
     Result.MLfit.muStd       , ...
     Result.MLfit.sigmaStd    , ...
     Result.MLfit.J_historyStd, ...
     Result.MLfit.errorStd]   = gradientDescent(Data.X, abs(Result.MLfit.errorMean), Config);
    
    
    Result.MLfit.fstd = @(x, y) Result.MLfit.thetaStd(1) + Result.MLfit.thetaStd(2)*x     + ...
                Result.MLfit.thetaStd(3)*y + Result.MLfit.thetaStd(4)*x^2 + ...
                Result.MLfit.thetaStd(5)*x*y + Result.MLfit.thetaStd(6)*y^2;

    
end